### ISSUE TITLE
[Bug]: Failure to buy a subscription on Polygon

### ISSUE THREAD

**Issue by gstricker** [nevermined-io/app#1]
### What happened?

The purchase process fails at the last step (90% mark) although payment and contract agreement have been successfully confirmed on-chain. 

### Network

Polygon Matic (Production) - <https://matic.nevermined.app>

### Metamask

Yes, Metamask is connected to the same network

### How To Reproduce?

Just try to purchase on the Polygon mainnet

### Links and transactions

App Website: https://matic.nevermined.app/en
Tx hash of Payment approval: 0xa3f21a2ee3f3ffe81a326f5fe1a09adb684658481234c8dfa5e8528d77bc2a16
Tx hash of Contract agreement approval: 0x7d89885d5f50d7c31ed6b57fc3e8f3b8de0a5489de50f6be9aa70c3c1577c2c3

### Screenshots and Additional context

<img width="615" alt="Screenshot 2023-06-28 at 14 17 21" src="https://github.com/nevermined-io/app/assets/10913698/30c8d6f6-6fe0-4ebc-93d2-39738533e75e">

**Comment by r-marques** [comment]
@gstricker can you share the full link to the subscription that you tried to buy?

**Comment by aaitor** [comment]
This 2 fail for me too: https://matic.nevermined.app/en/subscription/did:nv:0fae78438232e74f2777c0afa4e7b88bf3a04c49d0098edb0cc14dc8b08326ef
https://matic.nevermined.app/en/subscription/did:nv:b74d10e097a7c236a841cb8a438eb0cd188b38dcf407b91e7a243784583c2717

**Comment by gstricker** [comment]
> @gstricker can you share the full link to the subscription that you tried to buy?

Hmm, I honestly forgot which asset that was (it was actually two). But I reproduced it again with this asset:
https://matic.nevermined.app/en/dataset/did:nv:4597e66c2cac0d407b96383bd4afd576b2293ffd5653d45b43a927655395d76b
Payment TX: 0x1e2f7e2864fb77e7118619625f2292990bf3879390efa2f1a09dbc73bc4316c3
Contract agreement: 0x0762df72e94e5e64621c7304bfb784cb0f85bb1aa940da71c28ee13983fa050b

**Comment by aaitor** [comment]
This error was motivated because the wallet used for minting the subscriptions was having transactions stuck in Polygon. Once this was resolved all the NFT minting transactions were processed.
I tested the process manually and everything seems to work fine.
